<?php

declare(strict_types=1);

namespace Foodsoft\FirebirdDriver\Platform;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\Keywords\KeywordList;
use Doctrine\DBAL\Schema\AbstractSchemaManager;
use Foodsoft\FirebirdDriver\Platform\FirebirdKeywords;
use Doctrine\DBAL\Schema\Column;
use Doctrine\DBAL\Schema\Identifier;
use Doctrine\DBAL\Schema\Sequence;
use Doctrine\DBAL\Schema\TableDiff;
use Doctrine\DBAL\TransactionIsolationLevel;
use Doctrine\DBAL\Platforms\DateIntervalUnit;
use Doctrine\DBAL\Types\Type;
use UnexpectedValueException;

use function sprintf;

/**
 * Provides the behavior, features and SQL dialect of the Firebird database platform.
 */
class FirebirdPlatform extends AbstractPlatform
{
    // DBAL 2.13 does not support UnquotedIdentifierFolding configuration.

    public function getBooleanTypeDeclarationSQL(array $column): string
    {
        return 'SMALLINT';
    }

    public function getIntegerTypeDeclarationSQL(array $column): string
    {
        return 'INTEGER';
    }

    public function getBigIntTypeDeclarationSQL(array $column): string
    {
        return 'BIGINT';
    }

    public function getSmallIntTypeDeclarationSQL(array $column): string
    {
        return 'SMALLINT';
    }

    protected function _getCommonIntegerTypeDeclarationSQL(array $column): string
    {
        $autoinc = ! empty($column['autoincrement']) ? ' GENERATED BY DEFAULT AS IDENTITY' : '';

        return $autoinc;
    }

    public function getDateTimeTypeDeclarationSQL(array $column): string
    {
        return 'TIMESTAMP';
    }

    public function getDateTypeDeclarationSQL(array $column): string
    {
        return 'DATE';
    }

    public function getTimeTypeDeclarationSQL(array $column): string
    {
        return 'TIME';
    }

    protected function initializeDoctrineTypeMappings(): void
    {
        $this->doctrineTypeMapping = [
            'bigint'           => 'bigint',
            'blob'             => 'blob',
            'char'             => 'string',
            'date'             => 'date',
            'decimal'          => 'decimal',
            'double precision' => 'float',
            'float'            => 'float',
            'int'              => 'integer',
            'integer'          => 'integer',
            'numeric'          => 'decimal',
            'smallint'         => 'smallint',
            'time'             => 'time',
            'timestamp'        => 'datetime',
            'varchar'          => 'string',
        ];
    }

    public function getClobTypeDeclarationSQL(array $column): string
    {
        return 'BLOB SUB_TYPE TEXT';
    }

    public function getBlobTypeDeclarationSQL(array $column): string
    {
        return 'BLOB SUB_TYPE BINARY';
    }

    public function getName(): string
    {
        return 'firebird';
    }

    public function supportsSequences(): bool
    {
        return true;
    }

    public function supportsIdentityColumns(): bool
    {
        return true;
    }

    public function prefersSequences(): bool
    {
        return true;
    }

    public function getCurrentDatabaseExpression(): string
    {
        return "CAST(RDB\$GET_CONTEXT('SYSTEM', 'DB_NAME') AS VARCHAR(255))";
    }

    protected function getVarcharTypeDeclarationSQLSnippet(?int $length): string
    {
        if ($length === null) {
            return 'VARCHAR(255)';
        }

        return sprintf('VARCHAR(%d)', $length);
    }

    protected function getBinaryTypeDeclarationSQLSnippet(?int $length): string
    {
        return 'BLOB SUB_TYPE BINARY';
    }

    public function getCreateSequenceSQL(Sequence $sequence): string
    {
        return sprintf(
            'CREATE SEQUENCE %s START WITH %d INCREMENT BY %d',
            $sequence->getObjectName($this),
            $sequence->getInitialValue(),
            $sequence->getAllocationSize(),
        );
    }

    public function getAlterSequenceSQL(Sequence $sequence): string
    {
        return sprintf(
            'ALTER SEQUENCE %s RESTART WITH %d INCREMENT BY %d',
            $sequence->getQuotedName($this),
            $sequence->getInitialValue(),
            $sequence->getAllocationSize(),
        );
    }

    public function getDropSequenceSQL(string|Sequence $sequence): string
    {
        if ($sequence instanceof Sequence) {
            $sequence = $sequence->getQuotedName($this);
        }

        return 'DROP SEQUENCE ' . $sequence;
    }

    public function getSequenceNextValSQL(string $sequence): string
    {
        return sprintf('SELECT GEN_ID(%s, 1) FROM RDB$DATABASE', $sequence);
    }

    public function getSetTransactionIsolationSQL($level)
    {
        return sprintf(
            'SET TRANSACTION ISOLATION LEVEL %s',
            $this->_getTransactionIsolationLevelSQL($level)
        );
    }

    protected function _getTransactionIsolationLevelSQL($level)
    {
        switch ($level) {
            case TransactionIsolationLevel::READ_UNCOMMITTED:
                return 'READ COMMITTED RECORD_VERSION';
            case TransactionIsolationLevel::READ_COMMITTED:
                return 'READ COMMITTED NO RECORD_VERSION';
            case TransactionIsolationLevel::REPEATABLE_READ:
                return 'SNAPSHOT';
            case TransactionIsolationLevel::SERIALIZABLE:
                return 'SNAPSHOT TABLE STABILITY';
        }

        return parent::_getTransactionIsolationLevelSQL($level);
    }

    public function getReadLockSQL(): string
    {
        return 'WITH LOCK';
    }

    protected function getReservedKeywordsClass(): string
    {
        return FirebirdKeywords::class;
    }

    protected function createReservedKeywordsList(): KeywordList
    {
        return new FirebirdKeywords();
    }

    public function getListDatabasesSQL(): string
    {
        throw new UnexpectedValueException('Firebird does not support listing databases.');
    }

    public function getLocateExpression($string, $substring, $start = false)
    {
        if ($start === false) {
            return sprintf('POSITION(%s, %s)', $substring, $string);
        }

        return sprintf('POSITION(%s, %s, %s)', $substring, $string, $start);
    }

    public function getSubstringExpression($string, $start, $length = null)
    {
        if ($length === null) {
            return sprintf('SUBSTRING(%s FROM %s)', $string, $start);
        }

        return sprintf('SUBSTRING(%s FROM %s FOR %s)', $string, $start, $length);
    }

    public function supportsCommentOnStatement(): bool
    {
        return true;
    }

    public function hasNativeGuidType(): bool
    {
        return false;
    }

    public function getGuidTypeDeclarationSQL(array $column): string
    {
        return 'CHAR(36)';
    }

    public function getDateDiffExpression(string $date1, string $date2): string
    {
        return sprintf('DATEDIFF(DAY, %s, %s)', $date2, $date1);
    }

    protected function getDateArithmeticIntervalExpression($date, $operator, $interval, $unit)
    {
        $factorClause = $operator === '-' ? '-' : '';
        return sprintf('DATEADD(%s, %s%s, %s)', $unit, $factorClause, (string) $interval, $date);
    }

    public function getListViewsSQL(string $database): string
    {
        return "SELECT RDB\$RELATION_NAME AS viewname
                FROM RDB\$RELATIONS
                WHERE RDB\$VIEW_BLR IS NOT NULL
                  AND (RDB\$SYSTEM_FLAG IS NULL OR RDB\$SYSTEM_FLAG = 0)";
    }

    public function getAlterTableSQL(TableDiff $diff): array
    {
        $sql = [];
        $table = $diff->getOldTable();
        $tableNameSQL = $table->getQuotedName($this);

        foreach ($diff->getAddedColumns() as $addedColumn) {
            $query = 'ADD ' . $this->getColumnDeclarationSQL(
                $addedColumn->getQuotedName($this),
                $addedColumn->toArray(),
            );
            $sql[] = 'ALTER TABLE ' . $tableNameSQL . ' ' . $query;
        }

        foreach ($diff->getDroppedColumns() as $droppedColumn) {
            $query = 'DROP ' . $droppedColumn->getQuotedName($this);
            $sql[] = 'ALTER TABLE ' . $tableNameSQL . ' ' . $query;
        }

        foreach ($diff->getChangedColumns() as $columnDiff) {
            $oldColumn = $columnDiff->getOldColumn();
            $newColumn = $columnDiff->getNewColumn();

            $oldColumnName = $oldColumn->getQuotedName($this);

            if ($columnDiff->hasTypeChanged() || $columnDiff->hasLengthChanged() || $columnDiff->hasPrecisionChanged() || $columnDiff->hasScaleChanged()) {
                $sql[] = 'ALTER TABLE ' . $tableNameSQL . ' ALTER COLUMN ' . 
                         $this->getColumnDeclarationSQL($oldColumnName, $newColumn->toArray());
            }
        }

        foreach ($diff->getRenamedColumns() as $oldColumnName => $column) {
            $oldColumnName = new Identifier($oldColumnName);
            $sql[] = sprintf(
                'ALTER TABLE %s ALTER COLUMN %s TO %s',
                $tableNameSQL,
                $oldColumnName->getQuotedName($this),
                $column->getQuotedName($this),
            );
        }

        return array_merge($sql, parent::getAlterTableSQL($diff));
    }

    // For DBAL 2.13, SchemaManager is provided by the driver.
}
